{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Testing Object Localization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "import cv2\n",
    "from matplotlib.pyplot import imshow\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline\n",
    "import os\n",
    "\n",
    "os.environ[\"CUDA_VISIBLE_DEVICES\"] = str(0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import os\n",
    "import tensorflow as tf\n",
    "from handle_dataset import HandleDataFolder\n",
    "\n",
    "class Train:\n",
    "    __xs = []\n",
    "    __ys = []\n",
    "    __x_ = []\n",
    "    __y_box = []\n",
    "    __y_obj = []\n",
    "    __is_training = []\n",
    "    __model_box = []\n",
    "    __model_has_obj = []\n",
    "    __session = []\n",
    "    __train_step = []\n",
    "    __loss = []\n",
    "    __merged_summary_op = []\n",
    "    __writer = []\n",
    "    __saver = []\n",
    "\n",
    "    def build_graph(self):\n",
    "        self.__x_ = tf.placeholder(\"float\", shape=[None, 240, 320, 3], name='X')\n",
    "        self.__y_box = tf.placeholder(\"float\", shape=[None, 4], name='Y_box')\n",
    "        self.__y_obj = tf.placeholder(\"float\", shape=[None, 1], name='Y_obj')\n",
    "        # Add dropout to the fully connected layer\n",
    "        self.__is_training = tf.placeholder(tf.bool)\n",
    "\n",
    "        with tf.name_scope(\"model\") as scope:\n",
    "            conv1 = tf.layers.conv2d(inputs=self.__x_, filters=32, kernel_size=[5, 5],\n",
    "                                     padding=\"same\", activation=tf.nn.relu)\n",
    "\n",
    "            pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[2, 2], strides=2)\n",
    "\n",
    "            conv2 = tf.layers.conv2d(inputs=pool1, filters=64, kernel_size=[5, 5],\n",
    "                                     padding=\"same\", activation=tf.nn.relu)\n",
    "\n",
    "            pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[2, 2], strides=2)\n",
    "\n",
    "            conv3 = tf.layers.conv2d(inputs=pool2, filters=32, kernel_size=[5, 5],\n",
    "                                     padding=\"same\", activation=tf.nn.relu)\n",
    "\n",
    "            pool3 = tf.layers.max_pooling2d(inputs=conv3, pool_size=[2, 2], strides=2)\n",
    "\n",
    "            pool3_flat = tf.reshape(pool3, [-1, 40 * 30 * 32])\n",
    "\n",
    "            # 2 Head version (has object head, and bouding box)\n",
    "            self.__model_box = tf.layers.dense(inputs=pool3_flat, units=4)\n",
    "            self.__model_has_obj = tf.layers.dense(inputs=pool3_flat, units=1, activation=tf.nn.sigmoid)\n",
    "\n",
    "        with tf.name_scope(\"loss_func\") as scope:\n",
    "            loss_obj = tf.losses.log_loss(labels=self.__y_obj, predictions=self.__model_has_obj)\n",
    "            loss_bbox = tf.losses.huber_loss(labels=self.__y_box, predictions=self.__model_box)\n",
    "            # Get ratio of samples with objects\n",
    "            batch_size = tf.cast(tf.shape(self.__y_obj)[0], tf.float32)\n",
    "            num_objects_label = tf.cast(tf.count_nonzero(tf.cast(self.__y_obj > 0.0, tf.float32)), tf.float32)\n",
    "            print(num_objects_label)\n",
    "\n",
    "            ratio_has_objects = (num_objects_label * tf.constant(100.0)) / batch_size\n",
    "\n",
    "            # Loss function that has an \"ignore\" factor on the bbox loss when objects is not detected\n",
    "            self.__loss = loss_obj + (loss_bbox*ratio_has_objects)\n",
    "\n",
    "            # Add loss to tensorboard\n",
    "            tf.summary.scalar(\"loss\", self.__loss)\n",
    "            tf.summary.scalar(\"loss_bbox\", loss_bbox)\n",
    "            tf.summary.scalar(\"loss_obj\", loss_obj)\n",
    "\n",
    "        with tf.name_scope(\"optimizer\") as scope:\n",
    "            self.__train_step = tf.train.AdamOptimizer(1e-4).minimize(self.__loss)\n",
    "\n",
    "        # Merge op for tensorboard\n",
    "        self.__merged_summary_op = tf.summary.merge_all()\n",
    "\n",
    "        # Build graph\n",
    "        init = tf.global_variables_initializer()\n",
    "\n",
    "        # Saver for checkpoints\n",
    "        self.__saver = tf.train.Saver(max_to_keep=None)\n",
    "\n",
    "        # Avoid allocating the whole memory\n",
    "        gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.6)\n",
    "        self.__session = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))\n",
    "        # Configure summary to output at given directory\n",
    "        self.__writer = tf.summary.FileWriter(\"./logs/loc_logs\", self.__session.graph)\n",
    "        self.__session.run(init)\n",
    "\n",
    "    def train(self, path='./dataset/', save_dir='./save'):\n",
    "        data = HandleDataFolder()\n",
    "        self.__xs, self.__ys = data.load_dataset(path)\n",
    "        self.build_graph()\n",
    "        # Train\n",
    "        for i in range(2000):\n",
    "            if i % 100 == 0:\n",
    "                loss_val, summary = self.__session.run([self.__loss, self.__merged_summary_op],\n",
    "                                                       feed_dict={self.__x_: self.__xs,\n",
    "                                                                  self.__y_obj: self.__ys[:, 0].reshape(-1, 1),\n",
    "                                                                  self.__y_box: self.__ys[:, 1:],\n",
    "                                                                  self.__is_training: False})\n",
    "                print(\"Loss: {}\".format(loss_val))\n",
    "                # Write to tensorboard summary\n",
    "                self.__writer.add_summary(summary, i)\n",
    "            self.__train_step.run(session=self.__session,feed_dict={self.__x_: self.__xs,\n",
    "                                                                    self.__y_obj: self.__ys[:, 0].reshape(-1,1),\n",
    "                                                                    self.__y_box: self.__ys[:, 1:],\n",
    "                                                                    self.__is_training: False})\n",
    "        if not os.path.exists(save_dir):\n",
    "            os.makedirs(save_dir)\n",
    "        checkpoint_path = os.path.join(save_dir, \"model\")\n",
    "        filename = self.__saver.save(self.__session, checkpoint_path)\n",
    "        print(\"Model saved in file: %s\" % filename)\n",
    "\n",
    "    @property\n",
    "    def out_box(self):\n",
    "        return self.__model_box\n",
    "\n",
    "    @property\n",
    "    def out_has_obj(self):\n",
    "        return self.__model_has_obj\n",
    "\n",
    "    @property\n",
    "    def input(self):\n",
    "        return self.__x_\n",
    "\n",
    "    @property\n",
    "    def label_in_bbox(self):\n",
    "        return self.__y_box\n",
    "\n",
    "    @property\n",
    "    def label_in_obj(self):\n",
    "        return self.__y_obj\n",
    "\n",
    "    @property\n",
    "    def num_parameters(self):\n",
    "        return np.sum([np.prod(v.get_shape().as_list()) for v in tf.trainable_variables()])\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Load Test image"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAUoAAAD8CAYAAAARze3ZAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8QZhcZAAAWkElEQVR4nO3dfYwc9X3H8c93H84POCkGbLDsc20iK9gVlSEnTHBlpUmTgIXkREoqAmksZHGkIVIitX8QRdSpnD9MIakUiZI6CjKpaAjNAyCRtkFuKoQdDGe4EMC94CTGZxvOTVIgGOzbh2//2Jn17Hr3fue7253Zu/dLGu3sb2Z3vzd3/vg3v3lYc3cBANrLpV0AAGQdQQkAAQQlAAQQlAAQQFACQABBCQABHQtKM7vWzEbM7JCZ3d6pzwGATrNOnEdpZnlJv5T0YUlHJT0j6VPu/tKMfxgAdFinepRXSTrk7r9293FJD0ra0qHPAoCOKnTofZdLGk08PyppQ7uVzYzLgwCk7bfuvqTVgk4FpbVoawhDMxuUNNihzweAc/VKuwWdCsqjkvoTz1dIOp5cwd13Sdol0aMEkG2dGqN8RtIaM1ttZn2SbpD0aIc+CwA6qiM9Sncvm9nnJf2npLyk+9z9xU58FgB0WkdODzrnItj1BpC+A+4+0GoBV+YAQABBCQABBCUABBCUABBAUAJAAEEJAAEEJQAEEJQAEEBQAkAAQQkAAQQlAAQQlAAQQFACQABBCQABBCUABBCUABBAUAJAAEEJAAEEJQAEEJQAEEBQAkAAQQkAAQQlAAQQlAAQQFACQABBCQABBCUABBCUABBAUAJAAEEJAAEEJQAEEJQAEEBQAkAAQQkAAQQlAAQQlAAQUJjOi83ssKQ/SKpIKrv7gJldIOl7klZJOizpL939/6ZXJgCkZyZ6lH/u7uvdfSB6frukPe6+RtKe6DkA9KxO7HpvkXR/NH+/pI914DMAoGumG5Qu6SdmdsDMBqO2i939VUmKHpdO8zMAIFXTGqOUtNHdj5vZUkmPm9n/TPaFUbAOBlcEgJRNq0fp7sejxxOSfiTpKkljZrZMkqLHE21eu8vdBxJjmwCQSVMOSjM7z8zeFc9L+oikFyQ9KmlrtNpWSY9Mt0gASNN0dr0vlvQjM4vf51/d/T/M7BlJD5nZNklHJH1y+mUCQHrM3dOuQWaWfhEA5roD7YYCuTIHAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCAoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCAoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCAoASAAIISAAKCQWlm95nZCTN7IdF2gZk9bmYvR4+Lo3Yzs2+Y2SEze97Mruxk8QDQDZPpUe6WdG1T2+2S9rj7Gkl7oueSdJ2kNdE0KOnemSkTANITDEp3f0LS75uat0i6P5q/X9LHEu3f8ZqnJJ1vZstmqlgASMNUxygvdvdXJSl6XBq1L5c0mljvaNR2FjMbNLMhMxuaYg0A0BWFGX4/a9HmrVZ0912SdkmSmbVcBwCyYKo9yrF4lzp6PBG1H5XUn1hvhaTjUy8PANI31aB8VNLWaH6rpEcS7Z+Jjn5fLemNeBcdAHpVcNfbzL4r6QOSLjKzo5K2S9op6SEz2ybpiKRPRqv/WNJmSYckvS3p5g7UDABdZe7pDw8yRgkgAw64+0CrBVyZAwABBCUABBCUABBAUAJAAEEJAAEEJQAEEJQAEEBQAkAAQQkAAQQlAAQQlAAQQFACQABBCQABBCUABBCUABBAUAJAAEEJAAEEJQAEEJQAEEBQAkAAQQkAAQQlAAQQlAAQQFACQABBCQABBCUABBCUABBAUAJAAEEJAAEEJQAEEJQAEEBQAkAAQQkAAQQlAAQQlAAQQFACQEAwKM3sPjM7YWYvJNq+YmbHzGw4mjYnln3JzA6Z2YiZfbRThQNAt0ymR7lb0rUt2v/R3ddH048lyczWSbpB0p9Er/knM8vPVLEAkIZgULr7E5J+P8n32yLpQXc/7e6/kXRI0lXTqA8AUjedMcrPm9nz0a754qhtuaTRxDpHozYA6FlTDcp7Jb1H0npJr0r6WtRuLdb1Vm9gZoNmNmRmQ1OsAQC6YkpB6e5j7l5x96qkb+nM7vVRSf2JVVdIOt7mPXa5+4C7D0ylBgDolikFpZktSzz9uKT4iPijkm4ws3lmtlrSGklPT69EAEhXIbSCmX1X0gckXWRmRyVtl/QBM1uv2m71YUm3SpK7v2hmD0l6SVJZ0m3uXulM6QDQHebecgixu0WYpV8EgLnuQLuhQK7MAYAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCAoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEr0nFwuJ7PGb0aOn7drTz5v9XpgIsEvFwOyIpfLqVqtqlqtSqqFXjLwWn3/U3Idd69PwLkgKNEzqtVqvUdYrVYnFXpxqMbi18fLCE1MBkGJnlOpnP0NyGbWMjjj9pi711/P7jcmizFK9Iw42OIeYbLd3RuWx+OQyfZYvByYLP5a0DOSPcZ8Pt8w9iidCdJ4HLPV8nw+X1+H3W5MFrve6BnJIOzr69PKlSt1xRVXaO3atXrf+96nVatWaeXKlbrwwgslSc8995wOHz6sAwcO6ODBg3ruued07NgxjY+P19+PsMSkJI8EpjVJcqa5OZlZfcrlci6p/pjP5xvWk+QrVqzw4eFhT6pWqz6R5uXDw8P+2c9+1lesWFF/3+TnNdcR15f2tmLq+DTUNqPSDkmCcm5PrQKoOZjmz5/vN954ox87dsyr1apXKhWvVCpeKpUmDMhmpVKp/to4QG+88UafP39+288uFApt62SadRNByZSNKe61mVlDj7FQKNR7cPG0YMEC3759u586daoedK2ca4+y2alTp3z79u2+YMGChs+P64nDMp/P1wMzWTvTrJkISqZsTfPmzXPp7N3seBd8cHCwIRjjsEz2BpPzkwnKSqVSny+Xy16pVOrv614L4sHBQc/lcmftksd1xnUzzcqpbVBaFFSpiv4oMQfEJ4vHj0lmpuXLl2vv3r1auXKlJNXXTc671075iV8/mVN9kuvGr29eHr/PkSNHtHHjRh07dky5XK7hvM2J6kfPO+DuA60WcHoQuir+jzk+faevr68eWrfeeqtGR0fV39+vcrksSQ1BFYdc/B7nesJ48nShcrlcf59KpVIPyXK5rP7+fo2OjurWW2+tf3ZcZxyOWehgoHvoUaLrmk/LyefzeuKJJ3TNNddIauzdVSoV5fP5hl5gcj5eHpJcLxm08Xsllzf3Yp966ilt3Lixbf2YNdr2KAlKpCJ5zfWTTz6pDRs2ZPaSQndXsViUxInqsxy73siGOBzda9dcP/zww5kPSTPTww8/rEqlUg9JLoGcW/hto6uq1aqKxaLMTDt27ND111+f2ZCUzoxrXn/99dqxY4fMTMVikQM5cwy73uiqYrGoUqmkq666Svv379f4+Lj6+vrSLquteLwyrnPDhg16+umn6z8HZpWp73qbWb+Z/dTMDprZi2b2haj9AjN73Mxejh4XR+1mZt8ws0Nm9ryZXTmzPwt6WblcVl9fn/bs2SOpdjQ5y72zeBc7DvM9e/aor6+vflQec8Nkdr3Lkv7G3ddKulrSbWa2TtLtkva4+xpJe6LnknSdpDXRNCjp3hmvGj3L3XXXXXdp4cKFks702FrdYzIrKpVKPcwXLlyou+66iwM6c80UrqJ5RNKHJY1IWha1LZM0Es3/s6RPJdavr8eVOUxLliw562qaUqkUvLomLdVqtaG2eH7JkiWpb0umGZ/aXplzTgdzzGyVpCsk7Zd0sbu/KknR49JoteWSRhMvOxq1Abrzzjsbeo/ValWFQiGzB3Ti79xJDg9UKhXdeeedKVaFbpt0UJrZIkk/kPRFd39zolVbtHmL9xs0syEzG5psDegt8bmS8XTeeefp5ptvbrjpbq+cZhPXGd/89+abb9bChQvr7b34M2HyJvUbNbOiaiH5gLv/MGoeM7Nl0fJlkk5E7Ucl9SdevkLS8eb3dPdd7j7gbY4yobc1321ckg4cOJBmSTNuaGio4Qohj865dMYvZ53JHPU2Sd+WdNDdv55Y9KikrdH8VtXGLuP2z0RHv6+W9Ea8i465w8+MPyufz2vBggV673vfm3JVM2vt2rWaP39+w1VGyZ8bs8dkepQbJf2VpA+a2XA0bZa0U9KHzexl1Q7u7IzW/7GkX0s6JOlbkj4382WjFyR7W5dddtmsDJDLLruMOwnNAcHvzHH3J9V63FGSPtRifZd02zTrQg9LBkc8v2nTpswesJmOTZs21YcU4t3ufD6f6dOdcO4YdcaMS96lJz6QMzAwUP9Sr9miVCppYKA2xG5mKhRq/Y7Z2HOe6whKzLhSqVQ/Clwul1WtVnX55Zdn+lLFqSgWi7r88stVKBTk7vWfm93w2YdrvdER8W5ovOv99ttv1w98zBburlOnTtWvMkr+bFn4d4Vzxm3W0F3NQZE8z3C2iM+pjH+u+D8HQnL2ISjRUXFonD59OuVKOiP5cxGQsxdBiY6Kw+P48eOzbuyuWq3q+PHj9Z+RoJy9CEp0THJX+5577pl1l/blcjndc889ks79i87QW2bXXy4ya+/evWmX0BF79+4lJOcAghIzrlVwjIyMpFBJ542MjHAAZw4gKNExyfA4efJkPSzju4P3wphl8meI643rHxkZ0cmTJ896DT3M2YegxIyL76IjNYbGzp076/efbJblq3aaaysUCqpWq9q5s3Z7g/hKpPjelfQuZx9OOEdHJa97XrRokd588816mMRX7rQKzqyJ60zeSu3d73633nrrrfo6XOPd8zjhHN0T97Ck2u5q3Kt85513tHv37oZvL4zDJ6u74fElmMkwL5VK2r17t9555516W/Iu6MmfH7MDPUrMuHa3HTMzLV26VK+99pqkM/du7IXThuLAj0P/kksu0YkTJ1rerJfbrvUsepTonvibFaUzY5S5XE7urrGxMd19992SztxdyN0zvctaqVTqdUrS3XffrbGxsYb6pTNffUFIzj70KNFRhUJB5XK5HpjurkWLFml0dFTnn39+vU3K7tHi5MGp119/Xf39/XrrrbcafibpzM+KnkWPEumIgyN5ruHJkye1ePFiffWrX20Yw2xeL9kz69R/6K1O/2l1XqS7a8eOHVq8eHH9AE7zeoTkLNbue2y7OSn97/Nl6vJUKBQ8n8/7Y4895pVKxVuJ28fHx1sunynx+7eqo1wuu7v7Y4895vl83guFgkvyaC+IaXZNbb/Xm11vdF2xWKwf+c7lctq3b582bNigSqXScHf05GlEpVJJxWJxxmuJ37f58yQ11JO8IW9fX1+mz/vElLHrjewolUoN43vXXHON9u3bVw+j5JhmtVrtWEhKZ0I7DsHkXdnjkNy3b199FzuXyxGScxA9SqQqPuWmWq22HBfs5gGeVp/3wAMP6NOf/jRX3MwN9CiRHc2nDMUBdMstt9SfJw/yJNeZacn3Tga2u+uWW27R1q1b6+vlcrmG7/DG3EGPEqloPrXGzNTX16cLL7xQP/vZz7Ry5cqG8zG7If68I0eO6P3vf79+97vf6fTp02eNXWbh3ww6gh4lsiEOvrjXljx4c/r0aY2NjWnVqlXatm1bfd1On8Cd/A7ybdu2adWqVRobG2sIyXw+39D7pFc5x7Q7HN7NSemfFsCUkSk+7cbMfN68eX7HHXe4u3u1Wm04hadardbbmrVb1txeqVTqz++44w6fN29ew+envS2Yuj61PT0o9ZAkKJmap/hcxWKx6JI8l8v5TTfd5K+88oqXy2UvlUr1sCuVSvWwaw7CZHvza9xr50jedNNNnsvlGj4v/nymOTdxHiV6Q3ytdPIoc/L2ZfHyhQsX6pJLLtG6deu0fv16DQwMqL+/X6tXr9bixYslSc8++6xGR0c1NDSk4eFhvfTSS3rttdf09ttvN7xX8v2bv48cc0rbMUqCEpmRDKfmI+LJ5X19fSqVSg3jhROFWnK5malYLKpSqZx1I47kqUqTeV/MOhzMQfYl7/uYPOKdz+cb7gc5Pj5ePwqdvGJmovfN5/P13uL4+Hg9JAuFQv2AUjIY47uYAxJBiQzJ5/MNN5aIw6xSqdSvlokVCgWZWUOvMJfLNRyNTs5XKhWZ2Vl3Uy+Xyw2fk2znBryIEZTIjDiokt9BEz82n+jdHJzxLnPcE02OdcbiyyOTkjfjjR/jz8/yPTLRXVkZo/xfSScl/TbtWs7RRaLmbunFuqm5O2aq5j929yWtFmQiKCXJzIbaDaRmFTV3Ty/WTc3d0Y2a2fUGgACCEgACshSUu9IuYAqouXt6sW5q7o6O15yZMUoAyKos9SgBIJNSD0ozu9bMRszskJndnnY97ZjZYTP7hZkNm9lQ1HaBmT1uZi9Hj4szUOd9ZnbCzF5ItLWs02q+EW37583sygzV/BUzOxZt72Ez25xY9qWo5hEz+2hKNfeb2U/N7KCZvWhmX4jaM7utJ6g569t6vpk9bWY/j+r++6h9tZntj7b198ysL2qfFz0/FC1fNe0iUr5rUF7SryRdKqlP0s8lrUv7bkZtaj0s6aKmtn+QdHs0f7ukOzNQ5yZJV0p6IVSnpM2S/l2SSbpa0v4M1fwVSX/bYt110d/JPEmro7+ffAo1L5N0ZTT/Lkm/jGrL7LaeoOasb2uTtCiaL0raH23DhyTdELV/U9JfR/Ofk/TNaP4GSd+bbg1p9yivknTI3X/t7uOSHpS0JeWazsUWSfdH8/dL+liKtUiS3P0JSb9vam5X5xZJ3/GapySdb2bLulPpGW1qbmeLpAfd/bS7/0bSIdX+jrrK3V9192ej+T9IOihpuTK8rSeouZ2sbGt397eip8VockkflPT9qL15W8e/g+9L+pAlL9GagrSDcrmk0cTzo5r4F5cml/QTMztgZoNR28Xu/qpU+yOUtDS16ibWrs6sb//PR7up9yWGNTJXc7Rrd4VqPZ2e2NZNNUsZ39ZmljezYUknJD2uWu/2dXePr0lN1lavO1r+hqQLp/P5aQdlq5TP6mH4je5+paTrJN1mZpvSLmgGZHn73yvpPZLWS3pV0tei9kzVbGaLJP1A0hfd/c2JVm3RlkrdLWrO/LZ294q7r5e0QrVe7dpWq0WPM1532kF5VFJ/4vkKScdTqmVC7n48ejwh6Ueq/bLG4t2n6PFEehVOqF2dmd3+7j4W/eOoSvqWzuzyZaZmMyuqFjgPuPsPo+ZMb+tWNffCto65++uS/lu1McrzzSy+HVSytnrd0fI/0uSHdlpKOyifkbQmOnrVp9rA66Mp13QWMzvPzN4Vz0v6iKQXVKt1a7TaVkmPpFNhULs6H5X0meiI7NWS3oh3G9PWNH73cdW2t1Sr+YboyOZqSWskPZ1CfSbp25IOuvvXE4syu63b1dwD23qJmZ0fzS+Q9Beqja/+VNInotWat3X8O/iEpP/y6MjOlHX7CFaLI1qbVTv69itJX067njY1Xqra0b+fS3oxrlO1cY89kl6OHi/IQK3fVW33qaTa/6zb2tWp2i7KPdG2/4WkgQzV/C9RTc9Hf/jLEut/Oap5RNJ1KdX8Z6rtzj0vaTiaNmd5W09Qc9a39Z9Kei6q7wVJfxe1X6pacB+S9G+S5kXt86Pnh6Lll063Bq7MAYCAtHe9ASDzCEoACCAoASCAoASAAIISAAIISgAIICgBIICgBICA/weCXK3FavgY3gAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "#test_img = scipy.misc.imread('./test_data/test_0.jpg', mode=\"RGB\")\n",
    "test_img = cv2.imread('./test_data/test_1.jpg')\n",
    "plt.imshow(test_img)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Build Graph and Restore saved Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tensor(\"loss_func_3/Cast_2:0\", shape=(), dtype=float32)\n",
      "INFO:tensorflow:Restoring parameters from ./save/model\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n\nKey conv2d_10/bias not found in checkpoint\n\t [[node save_7/RestoreV2 (defined at <ipython-input-25-b403a95ac7aa>:8)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_7/Const_0_0, save_7/RestoreV2/tensor_names, save_7/RestoreV2/shape_and_slices)]]\n\t [[{{node save_7/RestoreV2/_135}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device_incarnation=1, tensor_name=\"edge_140_save_7/RestoreV2\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"]()]]\n\nCaused by op 'save_7/RestoreV2', defined at:\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n    app.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 505, in start\n    self.io_loop.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 148, in start\n    self.asyncio_loop.run_forever()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 438, in run_forever\n    self._run_once()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 1451, in _run_once\n    handle._run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\events.py\", line 145, in _run\n    self._callback(*self._args)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 690, in <lambda>\n    lambda f: self._run_callback(functools.partial(callback, future))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 743, in _run_callback\n    ret = callback()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 787, in inner\n    self.run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 748, in run\n    yielded = self.gen.send(value)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n    yield gen.maybe_future(dispatch(*args))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 272, in dispatch_shell\n    yield gen.maybe_future(handler(stream, idents, msg))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in execute_request\n    user_expressions, allow_stdin,\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2854, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2880, in _run_cell\n    return runner(coro)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n    coro.send(None)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3057, in run_cell_async\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3248, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3325, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-25-b403a95ac7aa>\", line 8, in <module>\n    saver = tf.train.Saver()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1102, in __init__\n    self.build()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1114, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1151, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 795, in _build_internal\n    restore_sequentially, reshape)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 406, in _AddRestoreOps\n    restore_sequentially)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 862, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\gen_io_ops.py\", line 1550, in restore_v2\n    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 488, in new_func\n    return func(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3274, in create_op\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1770, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nNotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n\nKey conv2d_10/bias not found in checkpoint\n\t [[node save_7/RestoreV2 (defined at <ipython-input-25-b403a95ac7aa>:8)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_7/Const_0_0, save_7/RestoreV2/tensor_names, save_7/RestoreV2/shape_and_slices)]]\n\t [[{{node save_7/RestoreV2/_135}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device_incarnation=1, tensor_name=\"edge_140_save_7/RestoreV2\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"]()]]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1333\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1334\u001b[1;33m       \u001b[1;32mreturn\u001b[0m \u001b[0mfn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1335\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mOpError\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[1;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n\u001b[0;32m   1318\u001b[0m       return self._call_tf_sessionrun(\n\u001b[1;32m-> 1319\u001b[1;33m           options, feed_dict, fetch_list, target_list, run_metadata)\n\u001b[0m\u001b[0;32m   1320\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_call_tf_sessionrun\u001b[1;34m(self, options, feed_dict, fetch_list, target_list, run_metadata)\u001b[0m\n\u001b[0;32m   1406\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_session\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moptions\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfeed_dict\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfetch_list\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtarget_list\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1407\u001b[1;33m         run_metadata)\n\u001b[0m\u001b[0;32m   1408\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNotFoundError\u001b[0m: Key conv2d_10/bias not found in checkpoint\n\t [[{{node save_7/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_7/Const_0_0, save_7/RestoreV2/tensor_names, save_7/RestoreV2/shape_and_slices)]]\n\t [[{{node save_7/RestoreV2/_135}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device_incarnation=1, tensor_name=\"edge_140_save_7/RestoreV2\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"]()]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\u001b[0m in \u001b[0;36mrestore\u001b[1;34m(self, sess, save_path)\u001b[0m\n\u001b[0;32m   1545\u001b[0m         sess.run(self.saver_def.restore_op_name,\n\u001b[1;32m-> 1546\u001b[1;33m                  {self.saver_def.filename_tensor_name: save_path})\n\u001b[0m\u001b[0;32m   1547\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mNotFoundError\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0merr\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m    928\u001b[0m       result = self._run(None, fetches, feed_dict, options_ptr,\n\u001b[1;32m--> 929\u001b[1;33m                          run_metadata_ptr)\n\u001b[0m\u001b[0;32m    930\u001b[0m       \u001b[1;32mif\u001b[0m \u001b[0mrun_metadata\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run\u001b[1;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1151\u001b[0m       results = self._do_run(handle, final_targets, final_fetches,\n\u001b[1;32m-> 1152\u001b[1;33m                              feed_dict_tensor, options, run_metadata)\n\u001b[0m\u001b[0;32m   1153\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_run\u001b[1;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1327\u001b[0m       return self._do_call(_run_fn, feeds, fetches, targets, options,\n\u001b[1;32m-> 1328\u001b[1;33m                            run_metadata)\n\u001b[0m\u001b[0;32m   1329\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1347\u001b[0m       \u001b[0mmessage\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0merror_interpolation\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0minterpolate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmessage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_graph\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1348\u001b[1;33m       \u001b[1;32mraise\u001b[0m \u001b[0mtype\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0me\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnode_def\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mop\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmessage\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1349\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNotFoundError\u001b[0m: Key conv2d_10/bias not found in checkpoint\n\t [[node save_7/RestoreV2 (defined at <ipython-input-25-b403a95ac7aa>:8)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_7/Const_0_0, save_7/RestoreV2/tensor_names, save_7/RestoreV2/shape_and_slices)]]\n\t [[{{node save_7/RestoreV2/_135}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device_incarnation=1, tensor_name=\"edge_140_save_7/RestoreV2\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"]()]]\n\nCaused by op 'save_7/RestoreV2', defined at:\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n    app.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 505, in start\n    self.io_loop.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 148, in start\n    self.asyncio_loop.run_forever()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 438, in run_forever\n    self._run_once()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 1451, in _run_once\n    handle._run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\events.py\", line 145, in _run\n    self._callback(*self._args)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 690, in <lambda>\n    lambda f: self._run_callback(functools.partial(callback, future))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 743, in _run_callback\n    ret = callback()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 787, in inner\n    self.run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 748, in run\n    yielded = self.gen.send(value)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n    yield gen.maybe_future(dispatch(*args))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 272, in dispatch_shell\n    yield gen.maybe_future(handler(stream, idents, msg))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in execute_request\n    user_expressions, allow_stdin,\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2854, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2880, in _run_cell\n    return runner(coro)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n    coro.send(None)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3057, in run_cell_async\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3248, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3325, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-25-b403a95ac7aa>\", line 8, in <module>\n    saver = tf.train.Saver()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1102, in __init__\n    self.build()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1114, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1151, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 795, in _build_internal\n    restore_sequentially, reshape)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 406, in _AddRestoreOps\n    restore_sequentially)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 862, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\gen_io_ops.py\", line 1550, in restore_v2\n    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 488, in new_func\n    return func(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3274, in create_op\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1770, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nNotFoundError (see above for traceback): Key conv2d_10/bias not found in checkpoint\n\t [[node save_7/RestoreV2 (defined at <ipython-input-25-b403a95ac7aa>:8)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_7/Const_0_0, save_7/RestoreV2/tensor_names, save_7/RestoreV2/shape_and_slices)]]\n\t [[{{node save_7/RestoreV2/_135}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device_incarnation=1, tensor_name=\"edge_140_save_7/RestoreV2\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"]()]]\n",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\u001b[0m in \u001b[0;36mrestore\u001b[1;34m(self, sess, save_path)\u001b[0m\n\u001b[0;32m   1555\u001b[0m       \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1556\u001b[1;33m         \u001b[0mnames_to_keys\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mobject_graph_key_mapping\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msave_path\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1557\u001b[0m       \u001b[1;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mNotFoundError\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\u001b[0m in \u001b[0;36mobject_graph_key_mapping\u001b[1;34m(checkpoint_path)\u001b[0m\n\u001b[0;32m   1829\u001b[0m   object_graph_string = reader.get_tensor(\n\u001b[1;32m-> 1830\u001b[1;33m       checkpointable.OBJECT_GRAPH_PROTO_KEY)\n\u001b[0m\u001b[0;32m   1831\u001b[0m   object_graph_proto = (\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36mget_tensor\u001b[1;34m(self, tensor_str)\u001b[0m\n\u001b[0;32m    370\u001b[0m         return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str),\n\u001b[1;32m--> 371\u001b[1;33m                                           status)\n\u001b[0m\u001b[0;32m    372\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\errors_impl.py\u001b[0m in \u001b[0;36m__exit__\u001b[1;34m(self, type_arg, value_arg, traceback_arg)\u001b[0m\n\u001b[0;32m    527\u001b[0m             \u001b[0mcompat\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mas_text\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mc_api\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mTF_Message\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 528\u001b[1;33m             c_api.TF_GetCode(self.status.status))\n\u001b[0m\u001b[0;32m    529\u001b[0m     \u001b[1;31m# Delete the underlying status object from memory otherwise it stays alive\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNotFoundError\u001b[0m: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-25-b403a95ac7aa>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      7\u001b[0m \u001b[0msess\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mInteractiveSession\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      8\u001b[0m \u001b[0msaver\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrain\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSaver\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 9\u001b[1;33m \u001b[0msaver\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrestore\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msess\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"./save/model\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     10\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Number of parameters:'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mmodel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mnum_parameters\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\u001b[0m in \u001b[0;36mrestore\u001b[1;34m(self, sess, save_path)\u001b[0m\n\u001b[0;32m   1560\u001b[0m         \u001b[1;31m# a helpful message (b/110263146)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1561\u001b[0m         raise _wrap_restore_error_with_msg(\n\u001b[1;32m-> 1562\u001b[1;33m             err, \"a Variable name or other graph key that is missing\")\n\u001b[0m\u001b[0;32m   1563\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1564\u001b[0m       \u001b[1;31m# This is an object-based checkpoint. We'll print a warning and then do\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNotFoundError\u001b[0m: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n\nKey conv2d_10/bias not found in checkpoint\n\t [[node save_7/RestoreV2 (defined at <ipython-input-25-b403a95ac7aa>:8)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_7/Const_0_0, save_7/RestoreV2/tensor_names, save_7/RestoreV2/shape_and_slices)]]\n\t [[{{node save_7/RestoreV2/_135}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device_incarnation=1, tensor_name=\"edge_140_save_7/RestoreV2\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"]()]]\n\nCaused by op 'save_7/RestoreV2', defined at:\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n    app.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 505, in start\n    self.io_loop.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 148, in start\n    self.asyncio_loop.run_forever()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 438, in run_forever\n    self._run_once()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 1451, in _run_once\n    handle._run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\events.py\", line 145, in _run\n    self._callback(*self._args)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 690, in <lambda>\n    lambda f: self._run_callback(functools.partial(callback, future))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 743, in _run_callback\n    ret = callback()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 787, in inner\n    self.run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 748, in run\n    yielded = self.gen.send(value)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n    yield gen.maybe_future(dispatch(*args))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 272, in dispatch_shell\n    yield gen.maybe_future(handler(stream, idents, msg))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in execute_request\n    user_expressions, allow_stdin,\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2854, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2880, in _run_cell\n    return runner(coro)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n    coro.send(None)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3057, in run_cell_async\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3248, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3325, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-25-b403a95ac7aa>\", line 8, in <module>\n    saver = tf.train.Saver()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1102, in __init__\n    self.build()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1114, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1151, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 795, in _build_internal\n    restore_sequentially, reshape)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 406, in _AddRestoreOps\n    restore_sequentially)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 862, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\gen_io_ops.py\", line 1550, in restore_v2\n    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 488, in new_func\n    return func(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3274, in create_op\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1770, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nNotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n\nKey conv2d_10/bias not found in checkpoint\n\t [[node save_7/RestoreV2 (defined at <ipython-input-25-b403a95ac7aa>:8)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_7/Const_0_0, save_7/RestoreV2/tensor_names, save_7/RestoreV2/shape_and_slices)]]\n\t [[{{node save_7/RestoreV2/_135}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device_incarnation=1, tensor_name=\"edge_140_save_7/RestoreV2\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"]()]]\n"
     ]
    }
   ],
   "source": [
    "model = Train()\n",
    "model.build_graph()\n",
    "model_in = model.input\n",
    "model_out_box = model.out_box\n",
    "model_out_has_obj = model.out_has_obj\n",
    "# Load tensorflow section\n",
    "sess = tf.InteractiveSession()\n",
    "saver = tf.train.Saver()\n",
    "saver.restore(sess, \"./save/model\")\n",
    "print('Number of parameters:',model.num_parameters)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Evaluate model on Image"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "ename": "FailedPreconditionError",
     "evalue": "Attempting to use uninitialized value conv2d_9/kernel\n\t [[node conv2d_9/kernel/read (defined at <ipython-input-23-880382dc5508>:31)  = Identity[T=DT_FLOAT, _class=[\"loc:@conv2d_9/kernel\"], _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"](conv2d_9/kernel)]]\n\t [[{{node model_3/dense_1/Sigmoid/_261}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device_incarnation=1, tensor_name=\"edge_56_model_3/dense_1/Sigmoid\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"]()]]\n\nCaused by op 'conv2d_9/kernel/read', defined at:\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n    app.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 505, in start\n    self.io_loop.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 148, in start\n    self.asyncio_loop.run_forever()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 438, in run_forever\n    self._run_once()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 1451, in _run_once\n    handle._run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\events.py\", line 145, in _run\n    self._callback(*self._args)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 690, in <lambda>\n    lambda f: self._run_callback(functools.partial(callback, future))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 743, in _run_callback\n    ret = callback()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 787, in inner\n    self.run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 748, in run\n    yielded = self.gen.send(value)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n    yield gen.maybe_future(dispatch(*args))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 272, in dispatch_shell\n    yield gen.maybe_future(handler(stream, idents, msg))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in execute_request\n    user_expressions, allow_stdin,\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2854, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2880, in _run_cell\n    return runner(coro)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n    coro.send(None)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3057, in run_cell_async\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3248, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3325, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-25-b403a95ac7aa>\", line 2, in <module>\n    model.build_graph()\n  File \"<ipython-input-23-880382dc5508>\", line 31, in build_graph\n    padding=\"same\", activation=tf.nn.relu)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\layers\\convolutional.py\", line 417, in conv2d\n    return layer.apply(inputs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py\", line 817, in apply\n    return self.__call__(inputs, *args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\layers\\base.py\", line 374, in __call__\n    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py\", line 746, in __call__\n    self.build(input_shapes)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\keras\\layers\\convolutional.py\", line 165, in build\n    dtype=self.dtype)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\layers\\base.py\", line 288, in add_weight\n    getter=vs.get_variable)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py\", line 609, in add_weight\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\checkpointable\\base.py\", line 639, in _add_variable_with_custom_getter\n    **kwargs_for_getter)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 1487, in get_variable\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 1237, in get_variable\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 540, in get_variable\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 492, in _true_getter\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 922, in _get_single_variable\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 183, in __call__\n    return cls._variable_v1_call(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 146, in _variable_v1_call\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 125, in <lambda>\n    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 2444, in default_variable_creator\n    expected_shape=expected_shape, import_scope=import_scope)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 187, in __call__\n    return super(VariableMetaclass, cls).__call__(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 1329, in __init__\n    constraint=constraint)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 1491, in _init_from_args\n    self._snapshot = array_ops.identity(self._variable, name=\"read\")\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\array_ops.py\", line 81, in identity\n    return gen_array_ops.identity(input, name=name)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\gen_array_ops.py\", line 4104, in identity\n    \"Identity\", input=input, name=name)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 488, in new_func\n    return func(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3274, in create_op\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1770, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nFailedPreconditionError (see above for traceback): Attempting to use uninitialized value conv2d_9/kernel\n\t [[node conv2d_9/kernel/read (defined at <ipython-input-23-880382dc5508>:31)  = Identity[T=DT_FLOAT, _class=[\"loc:@conv2d_9/kernel\"], _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"](conv2d_9/kernel)]]\n\t [[{{node model_3/dense_1/Sigmoid/_261}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device_incarnation=1, tensor_name=\"edge_56_model_3/dense_1/Sigmoid\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"]()]]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mFailedPreconditionError\u001b[0m                   Traceback (most recent call last)",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1333\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1334\u001b[1;33m       \u001b[1;32mreturn\u001b[0m \u001b[0mfn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1335\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mOpError\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[1;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n\u001b[0;32m   1318\u001b[0m       return self._call_tf_sessionrun(\n\u001b[1;32m-> 1319\u001b[1;33m           options, feed_dict, fetch_list, target_list, run_metadata)\n\u001b[0m\u001b[0;32m   1320\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_call_tf_sessionrun\u001b[1;34m(self, options, feed_dict, fetch_list, target_list, run_metadata)\u001b[0m\n\u001b[0;32m   1406\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_session\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moptions\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfeed_dict\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfetch_list\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtarget_list\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1407\u001b[1;33m         run_metadata)\n\u001b[0m\u001b[0;32m   1408\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mFailedPreconditionError\u001b[0m: Attempting to use uninitialized value conv2d_9/kernel\n\t [[{{node conv2d_9/kernel/read}} = Identity[T=DT_FLOAT, _class=[\"loc:@conv2d_9/kernel\"], _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"](conv2d_9/kernel)]]\n\t [[{{node model_3/dense_1/Sigmoid/_261}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device_incarnation=1, tensor_name=\"edge_56_model_3/dense_1/Sigmoid\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"]()]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mFailedPreconditionError\u001b[0m                   Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-26-5aa3aaf774a3>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mbox\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhas_obj\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0msess\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mmodel_out_box\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmodel_out_has_obj\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mfeed_dict\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m{\u001b[0m\u001b[0mmodel_in\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;33m[\u001b[0m\u001b[0mtest_img\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mbox\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mhas_obj\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m    927\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    928\u001b[0m       result = self._run(None, fetches, feed_dict, options_ptr,\n\u001b[1;32m--> 929\u001b[1;33m                          run_metadata_ptr)\n\u001b[0m\u001b[0;32m    930\u001b[0m       \u001b[1;32mif\u001b[0m \u001b[0mrun_metadata\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    931\u001b[0m         \u001b[0mproto_data\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf_session\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mTF_GetBuffer\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrun_metadata_ptr\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run\u001b[1;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1150\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mfinal_fetches\u001b[0m \u001b[1;32mor\u001b[0m \u001b[0mfinal_targets\u001b[0m \u001b[1;32mor\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mhandle\u001b[0m \u001b[1;32mand\u001b[0m \u001b[0mfeed_dict_tensor\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1151\u001b[0m       results = self._do_run(handle, final_targets, final_fetches,\n\u001b[1;32m-> 1152\u001b[1;33m                              feed_dict_tensor, options, run_metadata)\n\u001b[0m\u001b[0;32m   1153\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1154\u001b[0m       \u001b[0mresults\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_run\u001b[1;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1326\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mhandle\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1327\u001b[0m       return self._do_call(_run_fn, feeds, fetches, targets, options,\n\u001b[1;32m-> 1328\u001b[1;33m                            run_metadata)\n\u001b[0m\u001b[0;32m   1329\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1330\u001b[0m       \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_do_call\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0m_prun_fn\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhandle\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfeeds\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfetches\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1346\u001b[0m           \u001b[1;32mpass\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1347\u001b[0m       \u001b[0mmessage\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0merror_interpolation\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0minterpolate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmessage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_graph\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1348\u001b[1;33m       \u001b[1;32mraise\u001b[0m \u001b[0mtype\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0me\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnode_def\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mop\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmessage\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1349\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1350\u001b[0m   \u001b[1;32mdef\u001b[0m \u001b[0m_extend_graph\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mFailedPreconditionError\u001b[0m: Attempting to use uninitialized value conv2d_9/kernel\n\t [[node conv2d_9/kernel/read (defined at <ipython-input-23-880382dc5508>:31)  = Identity[T=DT_FLOAT, _class=[\"loc:@conv2d_9/kernel\"], _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"](conv2d_9/kernel)]]\n\t [[{{node model_3/dense_1/Sigmoid/_261}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device_incarnation=1, tensor_name=\"edge_56_model_3/dense_1/Sigmoid\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"]()]]\n\nCaused by op 'conv2d_9/kernel/read', defined at:\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n    app.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 505, in start\n    self.io_loop.start()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 148, in start\n    self.asyncio_loop.run_forever()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 438, in run_forever\n    self._run_once()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\base_events.py\", line 1451, in _run_once\n    handle._run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\asyncio\\events.py\", line 145, in _run\n    self._callback(*self._args)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 690, in <lambda>\n    lambda f: self._run_callback(functools.partial(callback, future))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\ioloop.py\", line 743, in _run_callback\n    ret = callback()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 787, in inner\n    self.run()\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 748, in run\n    yielded = self.gen.send(value)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n    yield gen.maybe_future(dispatch(*args))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 272, in dispatch_shell\n    yield gen.maybe_future(handler(stream, idents, msg))\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in execute_request\n    user_expressions, allow_stdin,\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 294, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2854, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2880, in _run_cell\n    return runner(coro)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n    coro.send(None)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3057, in run_cell_async\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3248, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3325, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-25-b403a95ac7aa>\", line 2, in <module>\n    model.build_graph()\n  File \"<ipython-input-23-880382dc5508>\", line 31, in build_graph\n    padding=\"same\", activation=tf.nn.relu)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\layers\\convolutional.py\", line 417, in conv2d\n    return layer.apply(inputs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py\", line 817, in apply\n    return self.__call__(inputs, *args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\layers\\base.py\", line 374, in __call__\n    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py\", line 746, in __call__\n    self.build(input_shapes)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\keras\\layers\\convolutional.py\", line 165, in build\n    dtype=self.dtype)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\layers\\base.py\", line 288, in add_weight\n    getter=vs.get_variable)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py\", line 609, in add_weight\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\training\\checkpointable\\base.py\", line 639, in _add_variable_with_custom_getter\n    **kwargs_for_getter)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 1487, in get_variable\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 1237, in get_variable\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 540, in get_variable\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 492, in _true_getter\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 922, in _get_single_variable\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 183, in __call__\n    return cls._variable_v1_call(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 146, in _variable_v1_call\n    aggregation=aggregation)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 125, in <lambda>\n    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 2444, in default_variable_creator\n    expected_shape=expected_shape, import_scope=import_scope)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 187, in __call__\n    return super(VariableMetaclass, cls).__call__(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 1329, in __init__\n    constraint=constraint)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 1491, in _init_from_args\n    self._snapshot = array_ops.identity(self._variable, name=\"read\")\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\array_ops.py\", line 81, in identity\n    return gen_array_ops.identity(input, name=name)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\ops\\gen_array_ops.py\", line 4104, in identity\n    \"Identity\", input=input, name=name)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 488, in new_func\n    return func(*args, **kwargs)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3274, in create_op\n    op_def=op_def)\n  File \"c:\\users\\sbyoon\\anaconda3\\envs\\tensor_1_12\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1770, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nFailedPreconditionError (see above for traceback): Attempting to use uninitialized value conv2d_9/kernel\n\t [[node conv2d_9/kernel/read (defined at <ipython-input-23-880382dc5508>:31)  = Identity[T=DT_FLOAT, _class=[\"loc:@conv2d_9/kernel\"], _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"](conv2d_9/kernel)]]\n\t [[{{node model_3/dense_1/Sigmoid/_261}} = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device_incarnation=1, tensor_name=\"edge_56_model_3/dense_1/Sigmoid\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"]()]]\n"
     ]
    }
   ],
   "source": [
    "box, has_obj = sess.run([model_out_box, model_out_has_obj],feed_dict={model_in: [test_img]})\n",
    "print(box)\n",
    "print(has_obj)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Draw Bounding Box"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "x: 159, y: 120, w: 32 h: 23\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAUoAAAD8CAYAAAARze3ZAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8QZhcZAAAWuUlEQVR4nO3de4xc5XnH8d8zl/UFJ8WADZa9rk1kBVNRGbLCBFdWmjQJWEhOpKQikMZCFksaIiVS+wdRRJ3K+cMUkkqRKKmjIJOKhtBcAIm0DXJTIexwWYNDAHeDkxivbVg3SYFgsHcuT/+Yc8ZnxjP7rnd35pyZ/X6koznznjMzz55d//y+5zbm7gIAtJdLuwAAyDqCEgACCEoACCAoASCAoASAAIISAAI6FpRmdo2ZjZrZQTO7rVOfAwCdZp04j9LM8pJ+KenDko5IekbSp9z9pVn/MADosE71KK+UdNDdf+3uE5IekLS5Q58FAB1V6ND7Lpc0lnh+RNL6diubGZcHAUjbb919SasFnQpKa9HWEIZmNixpuEOfDwBn65V2CzoVlEckDSaer5B0LLmCu++UtFOiRwkg2zq1j/IZSWvMbLWZDUi6XtIjHfosAOiojvQo3b1sZp+X9J+S8pLudfcXO/FZANBpHTk96KyLYOgNIH373H2o1QKuzAGAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCAoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCAoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCgMJMXm9khSX+QVJFUdvchMztP0vckrZJ0SNJfuvv/zaxMAEjPbPQo/9zd17n7UPT8Nkm73X2NpN3RcwDoWZ0Yem+WdF80f5+kj3XgMwCga2YalC7pJ2a2z8yGo7YL3f1VSYoel87wMwAgVTPaRylpg7sfM7Olkh4zs/+Z6gujYB0OrggAKZtRj9Ldj0WPxyX9SNKVksbNbJkkRY/H27x2p7sPJfZtAkAmTTsozewcM3tXPC/pI5JekPSIpC3RalskPTzTIgEgTTMZel8o6UdmFr/Pv7r7f5jZM5IeNLOtkg5L+uTMywSA9Ji7p12DzCz9IgDMdfva7QrkyhwACCAoASCAoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCAoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCAoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACAgGpZnda2bHzeyFRNt5ZvaYmb0cPS6O2s3MvmFmB83seTO7opPFA0A3TKVHuUvSNU1tt0na7e5rJO2OnkvStZLWRNOwpHtmp0wASE8wKN39cUm/b2reLOm+aP4+SR9LtH/Ha56UdK6ZLZutYgEgDdPdR3mhu78qSdHj0qh9uaSxxHpHorYzmNmwmY2Y2cg0awCArijM8vtZizZvtaK775S0U5LMrOU6AJAF0+1RjsdD6ujxeNR+RNJgYr0Vko5NvzwASN90g/IRSVui+S2SHk60fyY6+n2VpDfiIToA9Krg0NvMvivpA5IuMLMjkrZJ2iHpQTPbKumwpE9Gq/9Y0iZJByW9LemmDtQMAF1l7unvHmQfJYAM2OfuQ60WcGUOAAQQlAAQQFACQABBCQABBCUABBCUABBAUAJAAEEJAAEEJQAEEJQAEEBQAkDAbN+PEui6tG4U0Ormq+hP9CjR09K8mwp3cpk7CEoACGDojb7RraEwPcm5hx4lAAQQlAAQQFACQABBCQABBCUABBCUABBAUAJAAEEJAAEEJQAEEJQAEEBQAkAAQQkAAQQlAAQQlAAQQFACQABBCQABBCUABHCHc/QN7jyOTqFHCQABBCV6WppfGcvX1c4dDL3R8wgsdFqwR2lm95rZcTN7IdH2FTM7amb7o2lTYtmXzOygmY2a2Uc7VTgAdMtUht67JF3Tov0f3X1dNP1YkszsUknXS/qT6DX/ZGb52SoWANIQDEp3f1zS76f4fpslPeDup9z9N5IOSrpyBvUBQOpmcjDn82b2fDQ0Xxy1LZc0lljnSNQGAD1rukF5j6T3SFon6VVJX4vaW+1Xb3l6m5kNm9mImY1MswYA6IppBaW7j7t7xd2rkr6l08PrI5IGE6uukHSszXvsdPchdx+aTg0A0C3TCkozW5Z4+nFJ8RHxRyRdb2bzzGy1pDWSnp5ZiQCQruB5lGb2XUkfkHSBmR2RtE3SB8xsnWrD6kOSbpEkd3/RzB6U9JKksqRb3b3SmdIBoDvMPf0rZM0s/SIAzHX72u0K5BJGAAggKAEggKAEgACCEgACCEoACCAoASCAoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAggKAEggKAEgACCEgACCEoACCAoASCAoETPyeVyMmv8ZuT4ebv25PNWrwcmE/xyMSArcrmcqtWqqtWqpFroJQOv1fc/Jddx9/oEnA2CEj2jWq3We4TVanVKoReHaix+fbyM0MRUEJToOZXKmd+AbGYtgzNuj7l7/fUMvzFV7KNEz4iDLe4RJtvdvWF5vB8y2R6LlwNTxV8Lekayx5jP5xv2PUqngzTej9lqeT6fr6/DsBtTxdAbPSMZhAMDA1q5cqUuv/xyrV27Vu973/u0atUqrVy5Uueff74k6bnnntOhQ4e0b98+HThwQM8995yOHj2qiYmJ+vsRlpiS5JHAtCZJzjQ3JzOrT7lcziXVH/P5fMN6knzFihW+f/9+T6pWqz6Z5uX79+/3z372s75ixYr6+yY/r7mOuL60txVTx6eRthmVdkgSlHN7ahVAzcE0f/58v+GGG/zo0aNerVa9Uql4pVLxUqk0aUA2K5VK9dfGAXrDDTf4/Pnz2352oVBoWydT300EJVM2prjXZmYNPcZCoVDvwcXTggULfNu2bX7y5Ml60LVytj3KZidPnvRt27b5ggULGj4/ricOy3w+Xw/MZO1MfTMRlEzZmubNm+fSmcPseAg+PDzcEIxxWCZ7g8n5qQRlpVKpz5fLZa9UKvX3da8F8fDwsOdyuTOG5HGdcd1MfTm1DUqLgipV0R8l5oD4ZPH4McnMtHz5cu3Zs0crV66UpPq6yXn32ik/8euncqpPct349c3L4/c5fPiwNmzYoKNHjyqXyzWctzlZ/eh5+9x9qNUCTg9CV8X/Mcen7wwMDNRD65ZbbtHY2JgGBwdVLpclqSGo4pCL3+NsTxhPni5ULpfr71OpVOohWS6XNTg4qLGxMd1yyy31z47rjMMxCx0MdA89SnRd82k5+Xxejz/+uK6++mpJjb27SqWifD7f0AtMzsfLQ5LrJYM2fq/k8uZe7JNPPqkNGza0rR99o22PkqBEKpLXXD/xxBNav359Zi8pdHcVi0VJnKje5xh6IxvicHSvXXP90EMPZT4kzUwPPfSQKpVKPSS5BHJu4beNrqpWqyoWizIzbd++Xdddd11mQ1I6vV/zuuuu0/bt22VmKhaLHMiZYxh6o6uKxaJKpZKuvPJKPfXUU5qYmNDAwEDaZbUV76+M61y/fr2efvrp+s+BvjL9obeZDZrZT83sgJm9aGZfiNrPM7PHzOzl6HFx1G5m9g0zO2hmz5vZFbP7s6CXlctlDQwMaPfu3ZJqR5Oz3DuLh9hxmO/evVsDAwP1o/KYG6Yy9C5L+ht3XyvpKkm3mtmlkm6TtNvd10jaHT2XpGslrYmmYUn3zHrV6FnurjvvvFMLFy6UdLrH1uoek1lRqVTqYb5w4ULdeeedHNCZa6ZxFc3Dkj4saVTSsqhtmaTRaP6fJX0qsX59Pa7MYVqyZMkZV9OUSqXg1TVpqVarDbXF80uWLEl9WzLN+tT2ypyzOphjZqskXS7pKUkXuvurkhQ9Lo1WWy5pLPGyI1EboDvuuKOh91itVlUoFDJ7QCf+zp3k7oFKpaI77rgjxarQbVMOSjNbJOkHkr7o7m9OtmqLNm/xfsNmNmJmI1OtAb0lPlcyns455xzddNNNDTfd7ZXTbOI645v/3nTTTVq4cGG9vRd/JkzdlH6jZlZULSTvd/cfRs3jZrYsWr5M0vGo/YikwcTLV0g61vye7r7T3Ye8zVEm9Lbmu41L0r59+9IsadaNjIw0XCHk0TmXzv7LvjOVo94m6duSDrj71xOLHpG0JZrfotq+y7j9M9HR76skvREP0TF3+On9z8rn81qwYIHe+973plzV7Fq7dq3mz5/fcJVR8udG/5hKj3KDpL+S9EEz2x9NmyTtkPRhM3tZtYM7O6L1fyzp15IOSvqWpM/NftnoBcne1iWXXNKXAXLJJZdwJ6E5IPidOe7+hFrvd5SkD7VY3yXdOsO60MOSwRHPb9y4MbMHbGZi48aN9V0K8bA7n89n+nQnnD32OmPWJe/SEx/IGRoaqn+pV78olUoaGqrtYjczFQq1fkc/9pznOoISs65UKtWPApfLZVWrVV122WWZvlRxOorFoi677DIVCgW5e/3nZhjef7jWGx0RD0Pjoffbb79dP/DRL9xdJ0+erF9llPzZsvDvCmeN26yhu5qDInmeYb+Iz6mMf674PwdCsv8QlOioODROnTqVciWdkfy5CMj+RVCio+LwOHbsWN/tu6tWqzp27Fj9ZyQo+xdBiY5JDrXvvvvuvru0L5fL6e6775Z09l90ht7SX3+5yKw9e/akXUJH7Nmzh5CcAwhKzLpWwTE6OppCJZ03OjrKAZw5gKBExyTD48SJE/WwjO8O3gv7LJM/Q1xvXP/o6KhOnDhxxmvoYfYfghKzLr6LjtQYGjt27Kjff7JZlq/aaa6tUCioWq1qx47a7Q3iK5Hie1fSu+w/nHCOjkpe97xo0SK9+eab9TCJr9xpFZxZE9eZvJXau9/9br311lv1dbjGu+dxwjm6J+5hSbXhatyrfOedd7Rr166Gby+Mwyerw/D4EsxkmJdKJe3atUvvvPNOvS15F/Tkz4/+QI8Ss67dbcfMTEuXLtVrr70m6fS9G3vhtKE48OPQv+iii3T8+PGWN+vltms9ix4luif+ZkXp9D7KXC4nd9f4+LjuuusuSafvLuTumR6yViqVep2SdNddd2l8fLyhfun0V18Qkv2HHiU6qlAoqFwu1wPT3bVo0SKNjY3p3HPPrbdJ2T1anDw49frrr2twcFBvvfVWw88knf5Z0bPoUSIdcXAkzzU8ceKEFi9erK9+9asN+zCb10v2zDr1H3qr039anRfp7tq+fbsWL15cP4DTvB4h2cfafY9tNyel/32+TF2eCoWC5/N5f/TRR71SqXgrcfvExETL5bMlfv9WdZTLZXd3f/TRRz2fz3uhUHBJHo2CmPpravu93gy90XXFYrF+5DuXy2nv3r1av369KpVKw93Rk6cRlUolFYvFWa8lft/mz5PUUE/yhrwDAwOZPu8T08bQG9lRKpUa9u9dffXV2rt3bz2Mkvs0q9Vqx0JSOh3acQgm78oeh+TevXvrQ+xcLkdIzkH0KJGq+JSbarXacr9gNw/wtPq8+++/X5/+9Ke54mZuoEeJ7Gg+ZSgOoJtvvrn+PHmQJ7nObEu+dzKw3V0333yztmzZUl8vl8s1fIc35g56lEhF86k1ZqaBgQGdf/75+tnPfqaVK1c2nI/ZDfHnHT58WO9///v1u9/9TqdOnTpj32UW/s2gI+hRIhvi4It7bcmDN6dOndL4+LhWrVqlrVu31tft9Ancye8g37p1q1atWqXx8fGGkMzn8w29T3qVc0y7w+HdnJT+aQFMGZni027MzOfNm+e33367u7tXq9WGU3iq1Wq9rVm7Zc3tlUql/vz222/3efPmNXx+2tuCqetT29ODUg9JgpKpeYrPVSwWiy7Jc7mc33jjjf7KK694uVz2UqlUD7tSqVQPu+YgTLY3v8a9do7kjTfe6LlcruHz4s9nmnMT51GiN8TXSiePMidvXxYvX7hwoS666CJdeumlWrdunYaGhjQ4OKjVq1dr8eLFkqRnn31WY2NjGhkZ0f79+/XSSy/ptdde09tvv93wXsn3b/4+cswpbfdREpTIjGQ4NR8RTy4fGBhQqVRq2F84Wagll5uZisWiKpXKGTfiSJ6qNJX3Rd/hYA6yL3nfx+QR73w+33A/yImJifpR6OQVM5O9bz6fr/cWJyYm6iFZKBTqB5SSwRjfxRyQCEpkSD6fb7ixRBxmlUqlfrVMrFAoyMwaeoW5XK7haHRyvlKpyMzOuJt6uVxu+JxkOzfgRYygRGbEQZX8Dpr4sflE7+bgjIfMcU80ua8zFl8emZS8GW/8GH9+lu+Rie7Kyj7K/5V0QtJv067lLF0gau6WXqybmrtjtmr+Y3df0mpBJoJSksxspN2O1Kyi5u7pxbqpuTu6UTNDbwAIICgBICBLQbkz7QKmgZq7pxfrpubu6HjNmdlHCQBZlaUeJQBkUupBaWbXmNmomR00s9vSrqcdMztkZr8ws/1mNhK1nWdmj5nZy9Hj4gzUea+ZHTezFxJtLeu0mm9E2/55M7siQzV/xcyORtt7v5ltSiz7UlTzqJl9NKWaB83sp2Z2wMxeNLMvRO2Z3daT1Jz1bT3fzJ42s59Hdf991L7azJ6KtvX3zGwgap8XPT8YLV814yJSvmtQXtKvJF0saUDSzyVdmvbdjNrUekjSBU1t/yDptmj+Nkl3ZKDOjZKukPRCqE5JmyT9uySTdJWkpzJU81ck/W2LdS+N/k7mSVod/f3kU6h5maQrovl3SfplVFtmt/UkNWd9W5ukRdF8UdJT0TZ8UNL1Ufs3Jf11NP85Sd+M5q+X9L2Z1pB2j/JKSQfd/dfuPiHpAUmbU67pbGyWdF80f5+kj6VYiyTJ3R+X9Pum5nZ1bpb0Ha95UtK5ZrasO5We1qbmdjZLesDdT7n7byQdVO3vqKvc/VV3fzaa/4OkA5KWK8PbepKa28nKtnZ3fyt6Wowml/RBSd+P2pu3dfw7+L6kD1nyEq1pSDsol0saSzw/osl/cWlyST8xs31mNhy1Xejur0q1P0JJS1OrbnLt6sz69v98NEy9N7FbI3M1R0O7y1Xr6fTEtm6qWcr4tjazvJntl3Rc0mOq9W5fd/f4mtRkbfW6o+VvSDp/Jp+fdlC2SvmsHobf4O5XSLpW0q1mtjHtgmZBlrf/PZLeI2mdpFclfS1qz1TNZrZI0g8kfdHd35xs1RZtqdTdoubMb2t3r7j7OkkrVOvVrm21WvQ463WnHZRHJA0mnq+QdCylWibl7seix+OSfqTaL2s8Hj5Fj8fTq3BS7erM7PZ39/HoH0dV0rd0esiXmZrNrKha4Nzv7j+MmjO9rVvV3AvbOubur0v6b9X2UZ5rZvHtoJK11euOlv+Rpr5rp6W0g/IZSWuio1cDqu14fSTlms5gZueY2bvieUkfkfSCarVuiVbbIunhdCoMalfnI5I+Ex2RvUrSG/GwMW1N++8+rtr2lmo1Xx8d2VwtaY2kp1OozyR9W9IBd/96YlFmt3W7mntgWy8xs3Oj+QWS/kK1/as/lfSJaLXmbR3/Dj4h6b88OrIzbd0+gtXiiNYm1Y6+/UrSl9Oup02NF6t29O/nkl6M61Rtv8duSS9Hj+dloNbvqjZ8Kqn2P+vWdnWqNkS5O9r2v5A0lKGa/yWq6fnoD39ZYv0vRzWPSro2pZr/TLXh3POS9kfTpixv60lqzvq2/lNJz0X1vSDp76L2i1UL7oOS/k3SvKh9fvT8YLT84pnWwJU5ABCQ9tAbADKPoASAAIISAAIISgAIICgBIICgBIAAghIAAghKAAj4f14dss1WHaRvAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "y,x,w,h = box[0]\n",
    "x = int(x*320.0)\n",
    "y = int(y*240.0)\n",
    "w = int(w*320)\n",
    "h = int(h*240)\n",
    "print(\"x: %d, y: %d, w: %d h: %d\" % (x,y,w,h))\n",
    "cv2.rectangle(test_img, (x, y), (x + w, y + h), (255, 0, 0), 2)\n",
    "plt.imshow(test_img)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
